name: GitHub Actions
run-name: ${{ github.actor }} pushed a change via GitHub Actions 🚀
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  
  # scan:
  #   if: github.event_name == 'pull_request'
  #   permissions:
  #     contents: read # for actions/checkout to fetch code
  #     security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  #     actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v4

  #     - name: Checkov GitHub Action
  #       uses: bridgecrewio/checkov-action@v12
  #       with:
  #         quiet: true # optional: display only failed checks
  #         soft_fail: true # optional: do not return an error code if there are failed checks
  #         # This will add both a CLI output to the console and create a results.sarif file
  #         output_format: cli,sarif
  #         output_file_path: console,results.sarif
        
  #     - name: Upload SARIF file
  #       uses: github/codeql-action/upload-sarif@v3
        
  #       # Results are generated only on a success or failure
  #       # this is required since GitHub by default won't run the next step
  #       # when the previous one has failed. Security checks that do not pass will 'fail'.
  #       # An alternative is to add `continue-on-error: true` to the previous step
  #       # Or 'soft_fail: true' to checkov.
  #       if: success() || failure()
  #       with:
  #         sarif_file: results.sarif

  Plan:
    # if: github.event_name == 'pull_request'
    # needs: scan
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install -g aws-cdk

      - run: cdk --version

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7' 

      - run: mkdir cdk_max && cd cdk_max

      - run: cdk init sample-app --language python



